# Generated by Django 5.1.7 on 2025-03-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faculty_phone_number_faculty_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
    ]
