# Generated by Django 5.1.7 on 2025-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
